// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26.03.2026, 15:20:12
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/pr/bugaev_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/pr/bugaev_web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/pr/bugaev_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/pr/bugaev_web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/pr/bugaev_web/plugins/**/*.{js,ts,mjs}","D:/pr/bugaev_web/composables/**/*.{js,ts,mjs}","D:/pr/bugaev_web/utils/**/*.{js,ts,mjs}","D:/pr/bugaev_web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/pr/bugaev_web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/pr/bugaev_web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/pr/bugaev_web/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;